Repository ReCoded-Org/istanbul-capstone-sdp, pull requests merged in 2020-08, with the labels that each got.

#44 Footer
  src/components/common/Footer.jsx
  src/components/common/index.css
Labels: enhancement, styling

#47 About page content
  public/locales/en/translation.json
  src/components/About.jsx
  src/components/about/About.jsx
  src/components/about/index.css
  src/components/about/sections/AboutPageParags.jsx
  src/components/about/sections/CoFounders.jsx
  src/components/about/sections/Header.jsx
  src/components/about/sections/PeopleDisplay.jsx
  src/components/about/sections/PersonDisplay.jsx
  src/components/about/sections/WhoAreWe.jsx
  src/components/about/sections/images/staff0.png
  src/components/about/sections/images/staff1.png
  src/components/about/sections/images/staff2.png
  src/containers/App.jsx
Labels: enhancement, styling

#46 styling language selector
  package.json
  public/locales/ar/translation.json
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/App.test.js
  src/components/LangDropdown.jsx
  src/components/common/LangDropdown.jsx
  src/components/common/NavBar.jsx
  src/components/common/index.css
  src/components/images/lang.png
  src/components/langDropdown.css
  yarn.lock
Labels: enhancement, styling

#54 Contact us
  src/components/contact/Contact.jsx
  src/components/contact/images/contact-us-form.png
  src/components/contact/images/contact-us-header.png
  src/components/contact/index.css
  src/components/contact/sections/ContactUs.jsx
  src/components/contact/sections/Info.jsx
Labels: enhancement, styling

#56 create test structure, content
  package.json
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/components/common/NavBar.jsx
  src/containers/App.jsx
  src/containers/PsychoAssess/PsychoAssess.jsx
  src/containers/PsychoAssess/PsychoAssess.test.jsx
  src/containers/PsychoAssess/__snapshots__/PsychoAssess.test.jsx.snap
  src/containers/PsychoAssess/index.css
  src/containers/PsychoAssess/sections/Questions.jsx
Labels: enhancement, styling

#63 Live chat bot
  package.json
  src/components/home/Home.jsx
  src/containers/LiveChat.jsx
  src/containers/liveChat/LiveChat.jsx
  src/containers/liveChat/LiveChat.test.jsx
  src/containers/liveChat/__snapshots__/LiveChat.test.jsx.snap
  yarn.lock
Labels: documentation, enhancement

#51 create blogs layout
  package.json
  public/locales/en/translation.json
  src/components/blogs/Blogs.jsx
  src/components/blogs/index.css
  src/components/blogs/sections/BlogBox.jsx
  src/components/blogs/sections/BlogDisplay.jsx
  src/components/blogs/sections/BlogDisplay.test.jsx
  src/components/blogs/sections/BlogsDisplay.jsx
  src/components/blogs/sections/BlogsList.jsx
  src/components/blogs/sections/Header.jsx
  src/components/blogs/sections/__snapshots__/BlogDisplay.test.jsx.snap
  src/components/blogs/sections/images/blog0.jpg
  src/components/blogs/sections/images/blog1.jpg
  src/components/blogs/sections/images/blog2.jpg
  src/components/blogs/sections/images/blog3.jpg
  src/components/common/NavBar.jsx
  src/containers/App.jsx
Labels: enhancement, styling

#76 Bug bash gunsu
  public/index.html
  public/locales/en/translation.json
  public/manifest.json
  src/components/blogs/index.css
  src/components/common/Footer.jsx
  src/components/common/NavBar.jsx
  src/components/common/index.css
  src/components/home/index.css
  src/components/home/sections/RelatedCards.jsx
  src/containers/App.jsx
  src/containers/PsychoAssess/PsychoAssess.jsx
  src/containers/PsychoAssess/__snapshots__/PsychoAssess.test.jsx.snap
  src/containers/PsychoAssess/index.css
  src/containers/PsychoAssess/sections/Questions.jsx
Labels: bug

#77 translate assessment page to tr, fix keys to prevent conflict on home…
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/components/home/sections/Assessment.jsx
  src/containers/PsychoAssess/index.css
Labels: enhancement

#81 About Page translation
  public/locales/tr/translation.json
Labels: enhancement

#83 make donation translationable
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/containers/donation/Donation.jsx
Labels: enhancement

#86 Fix footer bug and make it responsive
  src/actions/actionTypes.jsx
  src/actions/authActions.jsx
  src/components/common/Footer.jsx
  src/components/common/index.css
  src/reducers/authReducer.jsx
Labels: bug, enhancement, styling

#82 Contact page translation
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/components/contact/sections/ContactUs.jsx
  src/components/contact/sections/Info.jsx
Labels: enhancement

#79 Assessment point system
  public/locales/en/translation.json
  src/components/home/sections/Assessment.jsx
  src/components/home/sections/WeCare.jsx
  src/containers/PsychoAssess/__snapshots__/PsychoAssess.test.jsx.snap
  src/containers/PsychoAssess/index.css
  src/containers/PsychoAssess/sections/Questions.jsx
Labels: enhancement, styling

#92 translate navbar to tr
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/components/common/NavBar.jsx
Labels: enhancement

#93 fix design for button
  src/containers/PsychoAssess/index.css
Labels: styling

#96 translate footer to tr
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/components/common/Footer.jsx
Labels: enhancement

#84 Fix contact form bug
  package.json
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/components/contact/index.css
  src/components/contact/sections/ContactUs.jsx
  src/components/contact/sections/Info.jsx
  yarn.lock
Labels: bug

#97 fix dropdown margin
  public/locales/en/translation.json
  public/locales/tr/translation.json
  src/components/common/LangDropdown.jsx
  src/components/common/index.css
  src/components/home/sections/Header.jsx
Labels: styling

#87 Blog editor
  package.json
  src/actions/actionTypes.jsx
  src/actions/blogActions.jsx
  src/components/common/roleConstants.jsx
  src/containers/BlogEditor/BlogEditor.css
  src/containers/BlogEditor/BlogEditor.jsx
  src/containers/profile/BlogBox.css
  src/containers/profile/BlogBox.jsx
  src/containers/profile/ManageBlogs.css
  src/containers/profile/ManageBlogs.jsx
  src/firebaseConfig.jsx
  src/reducers/blogReducer.jsx
  yarn.lock
Labels: documentation
